board/api/urls.py
from django.urls import path, include
from rest_framework import routers
from djoser.views import UserViewSet
from rest_framework_simplejwt.views import TokenObtainSlidingView, TokenRefreshSlidingView

from api.views import PostsViewset, GroupsViewset, CommentsViewset, FollowViewSet

app_name = 'api'

v1_router = routers.DefaultRouter()
v1_router.register(r'users', UserViewSet, basename='users')
v1_router.register(r'posts', PostsViewset, basename='posts')
v1_router.register(r'groups', GroupsViewset, basename='groups')
v1_router.register(
    r'posts/(?P<post_id>\d+)/comments',
    CommentsViewset,
    basename='comments'
)
v1_router.register(
    r'follow',
    FollowViewSet,
    basename='follow'
)

urlpatterns = [
    path('v1/', include(v1_router.urls)),
    path('token/get/', TokenObtainSlidingView.as_view(), name='jwt-get'),
    path('token/refresh/', TokenRefreshSlidingView.as_view(), name='jwt-refresh')
]

board/board/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import include, path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="board_api",
        default_version='v1',
        description="Board documentation",
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('api/', include('api.urls', namespace='api')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += [
    url(r'^swagger(?P<format>\.json|\.yaml)$',
        schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0),
        name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0),
        name='schema-redoc'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

board/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path(
        '',
        views.index,
        name='index'
    ),
    path(
        'group/<slug:slug>/',
        views.group_posts,
        name='group_list'
    ),
    path(
        'create/',
        views.PostCreateView.as_view(),
        name='post_create',
    ),
    path(
        'posts/<int:pk>/edit/',
        views.PostUpdateView.as_view(),
        name='post_edit',
    ),
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile'
    ),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail'
    ),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'follow/',
        views.follow_index,
        name='follow_index'
    ),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

board/users/urls.py
from django.contrib.auth import views
from django.urls import path, re_path


from .views import SignUp


app_name = 'users'

urlpatterns = [
    path(
        'signup/',
        SignUp.as_view(),
        name='signup'
    ),
    path(
        'logout/',
        views.LogoutView.as_view(
            template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        views.LoginView.as_view(
            template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_reset/',
        views.PasswordResetView.as_view(
            template_name='users/password_reset_form.html'),
        name='password_reset_form'
    ),
    path(
        'password_reset/done',
        views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    re_path(
        'reset/<uidb64>/<token>/',
        views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done',
        views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path(
        'password_change',
        views.PasswordChangeView.as_view(
            template_name='users/password_change_form.html'),
        name='password_change'
    ),
    path(
        'password_change/done/',
        views.PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
]

board/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

board/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

board/templates/users/base_form.html
{% extends "base.html" %}
{% block title %} Title {% endblock %}
{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% block header %} Card header {% endblock %}
        </div>
        <div class="card-body">
          {% block body %} Card body {% endblock %}
        </div>
      </div>
    </div>
</div>
{% endblock %}

board/templates/users/logged_out.html
{% extends "users/base_form.html" %}
{% block title %}You signed out{% endblock %}
{% block header %}
  Sign out
{% endblock %}
{% block body %}
  <p>
    You signed out of your account
  </p>
  <a class="btn btn-primary" href="{% url 'posts:index' %}">
    To main page
  </a>
{% endblock %}

board/templates/users/login.html
{% extends "users/base_form.html" %}
{% block title %} Sign in {% endblock %}
{% load user_filters %}
{% block header %} Sign in {% endblock %}
{% block body %}
  {% if form.errors %}
      {% for field in form %}
        {% for error in field.errors %}            
          <div class="alert alert-danger">
            {{ error|escape }}
          </div>
        {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
          {{ error|escape }}
        </div>
      {% endfor %}
  {% endif %}
  <form method="post"
    {% if action_url %}
      action="{% url action_url %}"
    {% endif %}
  >
  {% csrf_token %}
  {% for field in form %}
    <div class="form-group row my-3"
      {% if field.field.required %} 
        aria-required="true"
      {% else %}
        aria-required="false"
      {% endif %}
    >
      <label for="{{ field.id_for_label }}">
        {{ field.label }}
          {% if field.field.required %}
            <span class="required text-danger">*</span>
          {% endif %}
      </label>
      <div>
      {{ field|addclass:'form-control' }}
        {% if field.help_text %}
          <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
            {{ field.help_text|safe }}
          </small>
        {% endif %}
      </div>
    </div>
  {% endfor %}
  <div class="col-md-6 offset-md-4">
    <button type="submit" class="btn btn-primary">
      Sign in
    </button>
    <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
      Forgot your password?
    </a>
  </div>
  </form>
{% endblock %}

board/templates/users/password_change_done.html
{% extends "users/base_form.html" %}
{% block title %} Password changed {% endblock %}
{% load user_filters %}
{% block header %} Password changed {% endblock %}
{% block body %}
  <p>Password was successfully changed</p>
{% endblock %}

board/templates/users/password_change_form.html
{% extends "users/base_form.html" %}
{% block title %} Password change {% endblock %}
{% load user_filters %}
{% block header %} Password change {% endblock %}
{% block body %}
    <form method="post" action="{% url 'users:password_change' %}">
    {% csrf_token %}
      <div class="form-group row my-3 p-3">
        <label for="id_old_password">
          Old password
          <span class="required text-danger">*</span>
        </label>    
        <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
      </div>
      <div class="form-group row my-3 p-3">
        <label for="id_new_password1">
          New password
          <span class="required text-danger">*</span>
        </label>    
        <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
          <small id="id_new_password1-help" class="form-text text-muted">
            <ul>
              <li>Your password can't be too similar to your other personal information.</li>
              <li>Your password must contain at least 8 characters.</li>
              <li>Your password can't be a commonly used password.</li>
              <li>Your password can't be entirely numeric.</li>
            </ul>
          </small>
      </div>
      <div class="form-group row my-3 p-3">
        <label for="id_new_password2">
          Confirmation
          <span class="required text-danger">*</span>
        </label>    
        <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
      </div>
      <div class="col-md-6 offset-md-4">
        <button type="submit" class="btn btn-primary">
          Change password
        </button>
      </div>
    </form>
{% endblock %}

board/templates/users/password_reset_complete.html
{% extends "users/base_form.html" %}
{% block title %}Password reset was successful{% endblock %}
{% load user_filters %}
{% block header %} Password reset complete {% endblock %}
{% block body %}
  <p> Your new password is saved. Use it to log in. </p>
{% endblock %}

board/templates/users/password_reset_confirm.html
{% extends "users/base_form.html" %}
{% block title %} New password {% endblock %}
{% load user_filters %}
{% block header %}
    {% if validlink %}
    Enter new password
    {% else %}
    Error
    {% endif %}
{% endblock %}
{% block body %}
    {% if validlink %}
    <form method="post" action="{% url 'users:password_reset_confirm' %}">
    {% csrf_token %}
      <input type="hidden" name="csrfmiddlewaretoken" value="">
      <div class="form-group row my-3 p-3">
        <label for="id_new_password1">
          New password        
          <span class="required text-danger">*</span>        
        </label>    
        <input type="password" name="new_password1" class="form-control" required id="id_new_password1">      
        <small id="id_new_password1-help" class="form-text text-muted">
          <ul>
            <li>Your password can't contain your name or other personal information</li>
            <li>Your password should be at least 8 characters long</li>
            <li>Your password can't be too simple</li>
            <li>Your password can't only contain numbers</li>
          </ul>
        </small>      
      </div>
      <div class="form-group row my-3 p-3">
        <label for="id_new_password2">
          New password confirmation        
          <span class="required text-danger">*</span>        
        </label>    
        <input type="password" name="new_password2" class="form-control" required id="id_new_password2">      
      </div>
      <div class="col-md-6 offset-md-4">
        <button type="submit" class="btn btn-primary">
          Accept new password
        </button>
      </div>
    </form>
    {% else %}
    <p>Link is incorrect or expired</p>
    {% endif %}
{% endblock %}

board/templates/users/password_reset_done.html
{% extends "users/base_form.html" %}
{% block title %} Password reset completed {% endblock %}
{% load user_filters %}
{% block header %} Mail sent {% endblock %}
{% block body %}
  <p>Check your email, you should receive a confirmation email</p>
{% endblock %}

board/templates/users/password_reset_form.html
{% extends "users/base_form.html" %}
{% block title %} Password reset {% endblock %}
{% load user_filters %}
{% block header %}
  To reset your current password enter the email you registered with
{% endblock %}
{% block body %}
<div class="card-body"> 
  <form method="post" action="{% url 'users:password_reset_form' %}">
    {% csrf_token %}
    <div class="form-group row my-3 p-3">
      <label for="id_email">
        Email
        <span class="required text-danger">*</span>
      </label>    
      <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
    </div>
    <div class="col-md-6 offset-md-4">
      <button type="submit" class="btn btn-primary">
        Reset password
      </button>
    </div>
  </form>
{% endblock %}

board/templates/users/signup.html
{% extends "users/base_form.html" %}
{% block title %} Register {% endblock %}
{% load user_filters %}
{% block header %} Register {% endblock %}
{% block body %}
    {% if form.errors %}
        {% for field in form %} 
          {% for error in field.errors %}            
            <div class="alert alert-danger">
              {{ error|escape }}
            </div>
          {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
            {{ error|escape }}
          </div>
        {% endfor %}
    {% endif %}

    <form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    {% for field in form %} 
      <div class="form-group row my-3">
        <label for="{{ field.id_for_label }}">
          {{ field.label }}
            {% if field.field.required %}
              <span class="required text-danger">*</span>
            {% endif %}
        </label>
        {{ field|addclass:'form-control' }} 
          {% if field.help_text %}
            <small 
               id="{{ field.id_for_label }}-help"
               class="form-text text-muted"
            >
              {{ field.help_text|safe }}
            </small>
          {% endif %}
      </div>
    {% endfor %}
    <div class="col-md-6">
      <button type="submit" class="btn btn-primary">
        Register
      </button>
    </div>
    </form>
{% endblock %} 