board/api/urls.py
from django.urls import path, include
from rest_framework import routers
from djoser.views import UserViewSet
from rest_framework_simplejwt.views import TokenObtainSlidingView, TokenRefreshSlidingView

from api.views import PostsViewset, GroupsViewset, CommentsViewset, FollowViewSet

app_name = 'api'

v1_router = routers.DefaultRouter()
v1_router.register(r'users', UserViewSet, basename='users')
v1_router.register(r'posts', PostsViewset, basename='posts')
v1_router.register(r'groups', GroupsViewset, basename='groups')
v1_router.register(
    r'posts/(?P<post_id>\d+)/comments',
    CommentsViewset,
    basename='comments'
)
v1_router.register(
    r'follow',
    FollowViewSet,
    basename='follow'
)

urlpatterns = [
    path('v1/', include(v1_router.urls)),
    path('token/get/', TokenObtainSlidingView.as_view(), name='jwt-get'),
    path('token/refresh/', TokenRefreshSlidingView.as_view(), name='jwt-refresh')
]

board/board/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import include, path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="board_api",
        default_version='v1',
        description="Board documentation",
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('api/', include('api.urls', namespace='api')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += [
    url(r'^swagger(?P<format>\.json|\.yaml)$',
        schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0),
        name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0),
        name='schema-redoc'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

board/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path(
        '',
        views.index,
        name='index'
    ),
    path(
        'group/<slug:slug>/',
        views.group_posts,
        name='group_list'
    ),
    path(
        'create/',
        views.PostCreateView.as_view(),
        name='post_create',
    ),
    path(
        'posts/<int:pk>/edit/',
        views.PostUpdateView.as_view(),
        name='post_edit',
    ),
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile'
    ),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail'
    ),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'follow/',
        views.follow_index,
        name='follow_index'
    ),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

board/posts/models.py
from django.db import models
from django.db.models import F, Q
from django.contrib.auth import get_user_model
from django.shortcuts import reverse
from core.models import CreatedModel


POST_REPR = '{author} ({timestamp}): "{snippet}"'
User = get_user_model()


class Post(CreatedModel):
    text = models.TextField(
        'Post text',
        help_text='Text content of the post'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Author',
    )
    group = models.ForeignKey(
        'Group',
        on_delete=models.SET_NULL,
        related_name='posts',
        null=True,
        blank=True,
        verbose_name='Group',
        help_text='Associated group',
    )
    image = models.ImageField(
        'Image',
        upload_to='posts/',
        blank=True,
        help_text='Image file'
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return POST_REPR.format(
            author=self.author.username,
            timestamp=self.pub_date.strftime('%d/%m/%Y %H:%M'),
            snippet=self.text if len(self.text) <= 50 else self.text[:47] + '...'
        )

    def get_absolute_url(self):
        return reverse('posts:post_detail', args=(self.id,)) # type: ignore


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        related_name='comments',
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        User,
        related_name='comments',
        on_delete=models.CASCADE
    )
    text = models.TextField(
        'Comment text',
        help_text='Text content of the comment',
        default=None
    )


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=30, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:group_list', args=(self.slug,))


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user", "author"], name="unique_follow"
            ),
            models.CheckConstraint(
                check=~Q(user=F('author')), name="don't follow yourself"
            )
        ]

board/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        widgets = {
            'text': forms.Textarea(attrs={'cols': 40, 'rows': 10}),
        }
        labels = {
            'text': 'Text',
            'group': 'Group',
            'image': 'Image',
        }
        help_texts = {
            'text': 'Text',
            'group': 'Group to which the post belongs',
            'image': 'Choose an image to upload',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['group'].empty_label = 'Choose a group'


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        help_texts = {
            'text': 'Add a comment:',
        }

board/posts/views.py
from django.db import IntegrityError
from django.contrib import messages
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.shortcuts import render, reverse, redirect
from django.contrib.auth.decorators import login_required
from django.core.cache import cache

from .models import Group, Post, User, Follow
from .forms import PostForm, CommentForm
from .utils import get_page_obj


def index(request):
    page_num = request.GET.get('page')
    page_obj = cache.get_or_set(
        f'page-{page_num}',
        get_page_obj(Post.objects.all(), page_num),
        timeout=20)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/post_form.html'

    def get_success_url(self):
        return reverse(
            'posts:profile',
            kwargs={'username': self.request.user.username}
        )

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/post_form.html'

    def get_success_url(self):
        obj = self.get_object()
        return reverse(
            'posts:post_detail',
            kwargs={'post_id': obj.id}
        )

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if not request.user.is_authenticated:
            return redirect(reverse('users:login'))
        elif not obj.author == request.user:
            return redirect(
                reverse(
                    'posts:post_detail',
                    kwargs={'post_id': obj.id}
                )
            )
        return super().dispatch(request, *args, **kwargs)


def group_posts(request, slug):
    com_group = get_object_or_404(Group, slug=slug)
    page_num = request.GET.get('page')
    page_obj = get_page_obj(com_group.posts.all(), page_num)
    context = {
        'title': com_group.title,
        'description': com_group.description,
        'page_obj': page_obj,
        'group_name': com_group.title
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    following = (
        request.user.is_authenticated
        and User.objects.filter(following__author=author).exists()
    )
    page_num = request.GET.get('page')
    page_obj = get_page_obj(
        Post.objects.filter(author_id=author.id),
        page_num
    )
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'comments': post.comments.all(),
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def follow_index(request):
    page_num = request.GET.get('page')
    page_obj = get_page_obj(
        Post.objects.filter(author__following__user=request.user),
        page_num)
    context = {
        'title': 'Following',
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    try:
        follow = Follow.objects.create(user=request.user, author=author)
    except IntegrityError:
        messages.warning(request, "You can't follow yourself!")
    else:
        follow.save()
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    follow = Follow.objects.filter(user=request.user, author=author)
    follow.delete()
    return redirect('posts:profile', username=username)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)

board/templates/posts/follow.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
{{ title }}
{% endblock %}
{% load cache %}
{% cache 20 index_page %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
<div class="container py-5">     
  <h1>{{ title }}</h1>
  {% if not page_obj %}
  <h2> Winds howling </h2>
  {% endif %}
  {% for post in page_obj %}
  <article>
    <ul>
      <li>
        Author: {{ post.author.get_full_name }}
        <a href="{% url 'posts:profile' post.author.username %}"> all posts from author </a>
      </li>
      <li>
        Publication date: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
    <a href="{% url 'posts:post_detail' post.id %}"> details </a>
    <br>
    {% if post.group %} 
    <a href="{% url 'posts:group_list' post.group.slug %}"> All group posts </a>
    {% endif %}
  </article>
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}
{% endcache %}

board/templates/posts/group_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
{{ title }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ title }}</h1>
    <p>{{ description }}</p>
    <br>
    {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Author: {{ post.author.get_full_name }}
          <a href="{% url 'posts:profile' post.author.username %}"> all posts from author </a>
        </li>
        <li>
          Publication date: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
      <a href="{% url 'posts:post_detail' post.id %}"> details </a>
      <br>
      <a href="{% url 'posts:group_list' post.group.slug %}"> all group posts </a>
    </article>
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>  
{% endblock %}

board/templates/posts/index.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
Landing page
{% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
<div class="container">
  <h1>{{ title }}</h1>
  <hr>
  {% if not page_obj %}
  <h2> Winds howling... </h2>
  {% endif %}
  {% load cache %}
  {% cache 20 posts page_obj %}
  {% for post in page_obj %}
  <article>
    <div style="margin-bottom: 16px">
      <a class="postmark" style="display: block"
        href="{% url 'posts:post_detail' post.id %}">
        <span style="font-size: 12px; display: block">
          {{ post.author.get_full_name }} </span>
        <span style="font-size: 10px; display: block">
          {{ post.pub_date|date:"d E Y" }}
          {% if post.group %}
          | {{ post.group.title }}
          {% endif %}
        </span>
      </a>
    </div>
    <div class="row">
      {% thumbnail post.image "300x300" upscale="False" as im %}
      <div class="col-sm-3"
        style="
          width: fit-content;
          height: fit-content;"
        >
        <img src="{{ im.url }}" style="box-shadow: 0 0 3px 0 rgb(0 0 0 / 0.2)">
      </div>
      {% endthumbnail %}
      <div
        class="col-sm-9"
        style="
          width: fit-content;
          height: fit-content;"
        >
        <p>{{ post.text }}</p>
      </div>
    </div>
    <div style="margin-top: 16px">
      <span style="font-size: 12px; margin: 0 5px 0 0">
        <a
          class="postmark"
          href="{% url 'posts:profile' post.author.username %}">
          Author page
        </a>
      </span>
      {% if post.group %}
      <span style="font-size: 12px; margin: 0 5px 0 0">
        <a
          class="postmark"
          href="{% url 'posts:group_list' post.group.slug %}">
          Group page
        </a>
      </span>
      {% endif %}
    </div>
  </article>
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% endcache %}
  {% include 'posts/includes/paginator.html' %}
</div>
<style>
  .postmark {
    font-weight: 400;
    color: #435a6b;
    padding: 0 5px;
    width: fit-content;
    border-radius: 3px;
    box-shadow: 0.5px 0.5px 3px -1px #525252;
  }
  .postmark:hover {
    box-shadow: inset 0.5px 0.5px 3px -1px #525252;
    font-weight: 500;
    text-shadow: 0 0 1px #435a6b;
  }
</style>
{% endblock %}

board/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
Post {{ post.text|slice:":30" }}
{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Publication date: {{post.pub_date|date:"d E Y"}} 
        </li>
        {% if post.group %}  
          <li class="list-group-item">
            Group: {{post.group.title}}
            <a href="{% url 'posts:group_list' post.group.slug %}">
              all group's messages
            </a>
          </li>
        {% endif %}
          <li class="list-group-item">
            Author: {{ post.author }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Posts count:  <span > {{ post.author.posts.count }} </span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            All posts from author
          </a>
        </li>
      </ul>
    </aside>
  </div">
  <article class="col-12 col-md-9">
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>
     {{ post.text }}
    </p>
    {% if user == post.author %}
    <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
      edit post
    </a>
    {% endif %}
    {% include "posts/includes/comments.html" %}
  </article>
</div>
{% endblock %}

board/templates/posts/post_form.html
{% extends "base.html" %}
{% block title %}
  {% if is_edit %}      
    Edit post
  {% else %}
    New post
  {% endif %}
{% endblock %}
{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
              {% if post %}      
                Edit post
              {% else %}
                New post
              {% endif %}      
              </div>
              <div class="card-body">                     
                  {% if post %}
                  <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_edit' post.pk %}">
                  {% else %}
                  <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_create' %}">
                  {% endif %}
                  {% csrf_token %}
                  {% for field in form %}
                  <div class="form-group row my-3 p-3">
                    {{ field.label }}
                    {{ field }}
                    <small class="form-text text-muted">
                      {{ field.help_text }}              
                    </small>          
                  </div>            
                  {% endfor %}
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if post %}      
                        Save
                      {% else %}
                        Submit
                      {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

board/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}
{{ author.username }}'s profile
{% endblock %}
{% block content %}
  <div class="container py-5">        
    <div class="mb-5">
      <h1>All posts from {{ author.get_full_name }}</h1>
      <h3>Posts count {{ page_obj.paginator.count }}</h3>
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Unfollow
          </a>
        {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Follow
          </a>
        {% endif %}
    </div>
    {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Author: {{ author.username }}
        </li>
        <li>
          Publication date: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>
        {{ post.text }}
      </p>
      <a href="{% url 'posts:post_detail' post.id %}"> details </a>
    </article>
    {% if post.group %}  
    <a href="{% url 'posts:group_list' post.group.slug %}"> all group's messages </a>
    {% endif %}  
    {% if not forloop.last %} <hr> {% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

board/templates/posts/user_list.html
{% extends "base.html" %}
{% block title %}
{{title}}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ title }}</h1>
    <br>
    {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Author: {{ username }}
        </li>
        <li>
          Publication date: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text }}</p>
    </article>
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>  
{% endblock %}